name: Kong Conf
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - branch-test
    paths:
      - "kong-conf/**"
      - ".github/workflows/deploy-conf.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deck
        uses: kong/setup-deck@v1

      - name: Configure Deck
        run: |
          echo "KONNECT_TOKEN=${{ secrets.KONNECT_TOKEN }}" >> $GITHUB_ENV

      - name: Deck Dump
        run: |
          deck gateway dump --output-file=current.yaml \
            --konnect-token="$KONNECT_TOKEN" \
            --konnect-addr="https://us.api.konghq.com" \
            --konnect-control-plane-name="test-team1" \

      - name: Combine Kong Conf YAMLs
        run: |
          yq eval-all 'reduce .[] as $item ({}; . * $item)' kong-conf/**/*.yaml > kong-conf/all.yaml

      - name: Deck Merge
        run: |
          yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' current.yaml kong-conf/ > merged.yaml

      - name: Deck Diff
        run: |
          deck gateway diff kong-conf/ \
            --konnect-token="$KONNECT_TOKEN" \
            --konnect-addr="https://us.api.konghq.com" \
            --konnect-control-plane-name="test-team1"

      - name: Deck Sync
        run: |
          deck gateway sync merged.yaml \
            --konnect-token="$KONNECT_TOKEN" \
            --konnect-addr="https://us.api.konghq.com" \
            --konnect-control-plane-name="test-team1"
