name: Kong Conf
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - branch-test
    paths:
      - "kong-conf/**"
      - ".github/workflows/deploy-conf.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deck
        uses: kong/setup-deck@v1

      - name: Configure Deck
        run: |
          echo "KONNECT_TOKEN=${{ secrets.KONNECT_TOKEN }}" >> $GITHUB_ENV

      - name: Deck Diff
        run: |
          deck gateway diff kong-conf/kong.yaml \
            --konnect-token="$KONNECT_TOKEN" \
            --konnect-addr="https://us.api.konghq.com" \
            --konnect-control-plane-name="test-team1"

      - name: Deck Sync
        run: |
          deck gateway sync kong-conf/ \
            --konnect-token="$KONNECT_TOKEN" \
            --konnect-addr="https://us.api.konghq.com" \
            --konnect-control-plane-name="test-team1"
